In [1]:
import cv2
import numpy as np

In [3]:
img1 = cv2.imread("image_1.webp")  #read image
cv2.imshow("Image 1", img1) # show image
cv2.waitKey(5000) #image frame wait time-milisecond, pass 0 keyboard and key press
# cv2.destroyAllWindows() # all windows closes
cv2.destroyWindow("Image 1") #only one window closed


In [4]:
img1 = cv2.imread("image_1.webp")  
img2 = cv2.imread("image_2.jpg")  
cv2.imshow("Image 1", img1) 
cv2.imshow("Image 2", img2) 
cv2.waitKey(0) 
cv2.destroyAllWindows() 

In [14]:
img1 = cv2.imread("image_1.webp")  
img1 = cv2.resize(img1, (600,600)) #resize image
cv2.imshow("Image 1", img1)
cv2.waitKey(0) 
cv2.destroyAllWindows() 


In [18]:
img1 = cv2.imread("image_1.webp")  
print(img1)

[[[ 28  54  77]
  [ 17  39  61]
  [  0   4  24]
  ...
  [102 104 104]
  [ 95  97  97]
  [ 95  97  97]]

 [[ 28  54  77]
  [ 17  39  61]
  [  0   4  24]
  ...
  [102 104 104]
  [ 95  97  97]
  [ 95  97  97]]

 [[ 29  55  79]
  [ 18  40  62]
  [  0   5  25]
  ...
  [102 104 104]
  [ 95  97  97]
  [ 95  97  97]]

 ...

 [[151 152 150]
  [108 109 107]
  [ 74  73  71]
  ...
  [ 91  96 100]
  [ 41  46  50]
  [ 25  31  35]]

 [[ 86  89  93]
  [ 48  49  53]
  [ 40  38  43]
  ...
  [ 89  93  95]
  [ 63  67  69]
  [ 75  79  81]]

 [[  6  10  16]
  [ 20  23  29]
  [ 28  28  35]
  ...
  [ 11  16  15]
  [ 18  23  22]
  [ 15  19  19]]]


In [17]:
v = np.array([1,2,3,1,2,3])
np.hstack((v,v))

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [22]:
v = np.array([1,2,3,1,2,3])
np.vstack((v,v))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [24]:
img = cv2.imread("image_2.jpg")  
img = cv2.resize(img2, (300,300)) #resize image
h = np.hstack((img, img))
cv2.imshow("Image 2", h)
cv2.waitKey(0) 
cv2.destroyAllWindows() 

In [25]:
img = cv2.imread("image_2.jpg")  
img = cv2.resize(img2, (300,300)) #resize image
v = np.vstack((img, img))
cv2.imshow("Image 2", v)
cv2.waitKey(0) 
cv2.destroyAllWindows() 

In [26]:
img = cv2.imread("image_2.jpg")  
img = cv2.resize(img2, (300,300)) #resize image
h = np.hstack((img, img))
v = np.vstack((h,h))
cv2.imshow("Image 2", v)
cv2.waitKey(0) 
cv2.destroyAllWindows() 

In [3]:
image_list = ["image_1.webp","image_2.jpg","image_1.webp","image_2.jpg","image_1.webp",
              "image_2.jpg", "image_1.webp","image_2.jpg","image_1.webp","image_2.jpg"]
for name in image_list:
    img = cv2.imread(name)
    img = cv2.resize(img, (500, 500))
    cv2.imshow("Image Slidshow",img)
    cv2.waitKey(1000)
cv2.destroyAllWindows()    


In [4]:
image_list = ["image_1.webp","image_2.jpg","image_1.webp","image_2.jpg","image_1.webp",
              "image_2.jpg", "image_1.webp","image_2.jpg","image_1.webp","image_2.jpg"]
for name in image_list:
    img = cv2.imread(name)
    img = cv2.resize(img, (500, 500))
    cv2.imshow("Image Slidshow",img)
    cv2.waitKey(0)
cv2.destroyAllWindows()    


In [13]:
img1 = cv2.imread("image_1.webp")  
cv2.putText(img = img1,     #Put Text on Image
            text= "Men",
            org = (100,200),
            fontFace = cv2.FONT_HERSHEY_DUPLEX, 
            fontScale=3, 
            color = (0, 255, 0),  #BGR
            thickness = 3,
            lineType = cv2.LINE_8, 
            bottomLeftOrigin = False
        )
cv2.imshow("Image 1", img1)
cv2.waitKey(0) 
cv2.destroyAllWindows() 


In [31]:
img2 = cv2.imread("image_2.jpg") 
img2 = cv2.resize(img, (500,500)) 
cv2.line(img = img2,
        pt1 = (80,95),
        pt2 = (125,70),
        color =  (0,255,0),
        thickness = 3,
        lineType = 4,
    )
cv2.line(img = img2,
        pt1 = (125,70),
        pt2 = (174,60),
        color =  (0,255,0),
        thickness = 3,
        lineType = 4,
    )
cv2.imshow("Image 2", img2)
cv2.waitKey(0) 
cv2.destroyAllWindows() 


In [33]:
img2 = cv2.imread("image_2.jpg") 
img2 = cv2.resize(img, (500,500)) 
cv2.rectangle(img = img2,
        pt1 = (80,95),
        pt2 = (125,70),
        color =  (0,255,0),
        thickness = 3,
        lineType = 4,
    )

cv2.imshow("Image 2", img2)
cv2.waitKey(0) 
cv2.destroyAllWindows() 
