In [1]:
import cv2
import numpy as np

In [22]:
# Load an image
image = cv2.imread("image_1.png")

# Display image
cv2.imshow("Image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [23]:
# Load an image
image = cv2.imread("image_1.png")

# Display image
cv2.imshow("Image", image)
cv2.waitKey(5000)
cv2.destroyAllWindows()


In [44]:
img1 = cv2.imread("image_1.png")  
img2 = cv2.imread("image_2.png")  
cv2.imshow("Image 1", img1) 
cv2.imshow("Image 2", img2) 
cv2.waitKey(0) 
cv2.destroyAllWindows() 

In [26]:
# Read and write images
img = cv2.imread("image_1.png", cv2.IMREAD_COLOR)  # Color image
cv2.imwrite("image_2.jpg", img)  # Save as new file


True

In [27]:
# Resize
img = cv2.imread("image_1.png", cv2.IMREAD_COLOR)  
resized = cv2.resize(img, (300, 300))
cv2.imwrite("output.png", resized)  


True

In [ ]:
# Crop
img = cv2.imread("image_1.png", cv2.IMREAD_COLOR)  
cropped = img[50:200, 100:300]
cv2.imwrite("output.png", cropped)  


True

In [75]:
# Slider
import os
image_list = os.listdir("images")
for name in image_list:
    path = f"images\\{name}"
    img = cv2.imread(path)
    img = cv2.resize(img, (500, 500))
    cv2.imshow("Image Slidshow",img)
    cv2.waitKey(1000)
cv2.destroyAllWindows()    


In [76]:
# Slider
import os
image_list = os.listdir("images")
for name in image_list:
    path = f"images\\{name}"
    img = cv2.imread(path)
    img = cv2.resize(img, (500, 500))
    cv2.imshow("Image Slidshow",img)
    cv2.waitKey(0)
cv2.destroyAllWindows()    


In [46]:
img = cv2.imread("image_1.png", cv2.IMREAD_COLOR)  
print(img)

[[[234 250 249]
  [234 250 249]
  [234 250 249]
  ...
  [ 34  44  51]
  [ 33  41  48]
  [ 31  39  46]]

 [[234 250 249]
  [234 250 249]
  [234 250 249]
  ...
  [ 34  44  51]
  [ 34  42  49]
  [ 31  39  46]]

 [[234 250 249]
  [234 250 249]
  [233 249 248]
  ...
  [ 35  45  52]
  [ 34  42  49]
  [ 31  39  46]]

 ...

 [[141 155 153]
  [142 156 154]
  [143 157 155]
  ...
  [ 70  77  80]
  [ 65  72  75]
  [ 66  73  76]]

 [[140 154 152]
  [140 154 152]
  [141 155 153]
  ...
  [ 74  81  84]
  [ 73  80  83]
  [ 76  83  86]]

 [[140 154 152]
  [139 153 151]
  [139 153 151]
  ...
  [ 73  80  83]
  [ 76  83  86]
  [ 82  89  92]]]


In [48]:
h = np.array([1,2,3,1,2,3])
np.hstack((h,h))

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [54]:
v = np.array([1,2,3,1,2,3])
np.vstack((v,v))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [ ]:
# join image horizontally
img = cv2.imread("image_1.png")  
img = cv2.resize(img, (300,300)) 
h = np.hstack((img, img))
cv2.imwrite("output.png", h) 

True

In [ ]:
# join inage vertically
img = cv2.imread("image_1.png")  
img = cv2.resize(img, (300,300)) 
v = np.vstack((img, img))
cv2.imwrite("output.png", v) 

True

In [ ]:
# join horizontally and verically both
img = cv2.imread("image_1.png")  
img = cv2.resize(img, (300,300)) 
h = np.hstack((img, img))
v =np.vstack((h,h))
cv2.imwrite("output.png", v) 

True

In [61]:
# Color Conversion : GrayScale
img = cv2.imread("image_1.png", cv2.IMREAD_COLOR)  
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imwrite("output.png", gray)  


True

In [31]:
# Color Conversion : HSV
img = cv2.imread("image_1.png", cv2.IMREAD_COLOR)  
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
cv2.imwrite("output.png", hsv)  

True

In [67]:
# Add Text
img = cv2.imread("image_1.png") 
img = cv2.resize(img, (500,500))  
cv2.putText(img,     #Put Text on Image
            text= "Men",
            org = (100,200),
            fontFace = cv2.FONT_HERSHEY_DUPLEX, 
            fontScale=3, 
            color = (0, 255, 0),  #BGR
            thickness = 3,
            lineType = cv2.LINE_8, 
            bottomLeftOrigin = False
)            
cv2.imwrite("output.png", img)  


True

In [68]:
# Drae Shape : Line
img = cv2.imread("image_1.png") 
img = cv2.resize(img, (500,500)) 
cv2.line(img,
        pt1 = (80,95),
        pt2 = (125,70),
        color =  (0,255,0),
        thickness = 3,
        lineType = 4,
    )
cv2.line(img,
        pt1 = (125,70),
        pt2 = (174,60),
        color =  (0,255,0),
        thickness = 3,
        lineType = 4,
    )
cv2.imwrite("output.png", img)  


True

In [70]:
# Drae Shape : Rectangle
img = cv2.imread("image_1.png") 
img = cv2.resize(img, (500,500)) 
cv2.rectangle(img,
        pt1 = (60,15),
        pt2 = (255,180),
        color =  (0,255,0),
        thickness = 3,
        lineType = 4,
    )
cv2.imwrite("output.png", img)  

True

In [71]:
# Drae Shape : Circle
img = cv2.imread("image_1.png") 
img = cv2.resize(img, (500,500)) 
cv2.circle(img,
        center = (160,100),
        radius = 95,
        color =  (0,255,0),
        thickness = 4,
        lineType = 16,
    )
cv2.imwrite("output.png", img) 

True

In [72]:
# Drae Shape : Ellipse
img = cv2.imread("image_1.png") 
img = cv2.resize(img, (500,500)) 
cv2.ellipse(img,
        center = (160,100),
        axes = (90,100),
        angle = -40,
        startAngle = 0,
        endAngle =  360,
        color=(0,0, 255),
        thickness = 4,
        lineType = 16,
    )
cv2.imwrite("output.png", img) 

True

In [73]:
# Drae Shape : Polygon
img = cv2.imread("image_1.png") 
img = cv2.resize(img, (500,500)) 
cv2.polylines(img,
              pts= [np.array([ [150,60], [100,150], [100,300], [150,100], [150,200] ])],
              isClosed= True,
              color= (0,0,255),
              thickness= 4,
              lineType= 4
    )
cv2.imwrite("output.png", img) 

True

In [33]:
# Rotate image
img = cv2.imread("image_1.png", cv2.IMREAD_COLOR)  
rows, cols = img.shape[:2]
M = cv2.getRotationMatrix2D((cols/2, rows/2), 45, 1)  # 45 degrees
rotated = cv2.warpAffine(img, M, (cols, rows))
cv2.imwrite("output.png", rotated)

True

In [37]:
# Perspective Transform
img = cv2.imread("image_1.png", cv2.IMREAD_COLOR)  
pts1 = np.float32([[0, 0], [300, 0], [0, 300], [300, 300]])
pts2 = np.float32([[0, 0], [200, 50], [50, 250], [250, 250]])
M = cv2.getPerspectiveTransform(pts1, pts2)
dst = cv2.warpPerspective(img, M, (300, 300))

cv2.imwrite("output.png", dst)

True

In [ ]:
# Blurring
img = cv2.imread("image_1.png", cv2.IMREAD_COLOR) 
blur = cv2.GaussianBlur(img, (5, 5), 0)
cv2.imwrite("output.png", blur)


True

In [3]:
# Thresholding
img = cv2.imread("image_1.png", cv2.IMREAD_COLOR) 
_, thresh = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)
cv2.imwrite("output.png", thresh)


True

In [40]:
# Edge Detection (Canny Edge Detector)
img = cv2.imread("image_1.png", cv2.IMREAD_COLOR) 
edges = cv2.Canny(img, 100, 200)
cv2.imwrite("output.png", edges)

True

In [43]:
# Contours
img = cv2.imread("image_1.png", cv2.IMREAD_COLOR) 
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
cv2.drawContours(img, contours, -1, (0, 255, 0), 2)
cv2.imwrite("output.png", hierarchy)

True

In [81]:
# Capture video from webcam
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    if not ret:
        break
    cv2.imshow("Video", frame)
    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()


In [82]:
# Convert Video to Grayscale
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    if not ret:
        break
    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # gray = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    cv2.imshow('Grayscale Video', gray)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()


In [84]:
# Face Detection
cap = cv2.VideoCapture(0)
face_cap = cv2.CascadeClassifier(r"env\Lib\site-packages\cv2\data\haarcascade_frontalface_default.xml")

while True:
    ret, frame = cap.read()
    col = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_cap.detectMultiScale(col,
                                      scaleFactor=1.1,
                                      minNeighbors= 5,
                                      minSize= (30,30), 
                                      flags= cv2.CASCADE_SCALE_IMAGE
                                      )
    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y), (x+w, y+h), (0,255,0),2)
    
    cv2.imshow("Video Live", frame)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()    
cv2.destroyAllWindows()