In [13]:
import numpy as np
import pandas as pd

# NumPy Arrays

In [ ]:
arr = np.array([1, 2, 3, 4, 5])  # 1D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
print(arr)
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


# Basic Operations

In [ ]:
arr = np.array([1, 2, 3])
result = arr + 2 
print(result)
result = arr * 3  
print(result)
result = arr ** 2  
print(result)


[3 4 5]
[3 6 9]
[1 4 9]


In [5]:
# Array Addition & Multiplication
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)
result = arr1 * arr2  
print(result)


[5 7 9]
[ 4 10 18]


In [6]:
# Matrix Multiplication:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
result = np.dot(mat1, mat2)
result


array([[19, 22],
       [43, 50]])

# Slicing

In [7]:
arr = np.array([10, 20, 30, 40, 50])
slice1 = arr[1:4] 
print(slice1)

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
slice2 = arr_2d[1:, 1:]
print(slice2)


[20 30 40]
[[5 6]
 [8 9]]


# Indexing

In [8]:
# Basic Indexing
arr = np.array([10, 20, 30])
value = arr[1]  
print(value)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
value = arr_2d[1, 2]  
print(value)


20
6


In [11]:
# Boolean Indexing
arr = np.array([10, 20, 30, 40])
filtered = arr[arr > 20] 
filtered


array([30, 40])

# Filtering

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6])
filtered_arr = arr[arr % 2 == 0]  
filtered_arr

array([2, 4, 6])